name: C/C++ CI
  
on: [push]
jobs:
  build_gcc:
    name: Ubuntu GCC build and unit tests
    runs-on: ubuntu-18.04
    steps:
    - name: Install Boost and lcov
      run:  sudo apt install libboost-all-dev lcov
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run:  cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .
    - name: Build
      run:  make -j $(nproc)
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test
    - name: Coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
        lcov --list coverage.info # debug info
        # Uploading report to CodeCov
        curl -s https://codecov.io/bash | bash -s -- -f coverage.info || echo "Codecov did not collect coverage reports"

  build_clang:
    name: MacOS Clang build and unit tests
    runs-on: macOS-latest
    steps:
    - name: Install Boost
      run:  brew install boost
    - name: Clone repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run:  cmake .
    - name: Build
      run:  make -j 4
    - name: Unit tests
      run:  env CTEST_OUTPUT_ON_FAILURE=1 make test
